name: Schedule Test

on:
  schedule:
    - cron: '55 16 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduler
        run: |
          echo "GitHub scheduled workflow triggered"
          date -u